version: "2"
linters:
  enable:
    - gosec
    - misspell
    - revive
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 12
    gosec:
      excludes:
        - G104
        - G307
        - G304
        - G204
    misspell:
      locale: US
      ignore-rules:
        - listend
        - analyses
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'package-comments: should have a package comment'
      - linters:
          - errcheck
        text: Error return value of `g.DeleteView` is not checked
      - linters:
          - errcheck
        text: Error return value of `g.SetCurrentView` is not checked
      - linters:
          - errcheck
        text: Error return value of `*.SetCursor` is not checked
      - linters:
          - govet
        text: declaration of "err" shadows declaration at *
      - linters:
          - govet
        text: declaration of "ctx" shadows declaration at *
      - linters:
          - revive
        path: internal/pkg/keybindings/listhandlers.go
      - linters:
          - revive
        path: internal/pkg/keybindings/commandpanelhandlers.go
      - linters:
          - revive
        path: internal/pkg/keybindings/itemhandlers.go
      - linters:
          - revive
        path: internal/pkg/keybindings/globalhandlers.go
      - linters:
          - revive
        path: internal/pkg/*
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
