builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/azbrowse/
  ldflags:
   - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X "main.goversion={{.Env.GOVERSION}}"

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
  - goos: windows
    format: zip

nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/lawrencegripper/azbrowse
  description: An interactive CLI for browsing Azure, inspired by http://resources.azure.com/
  maintainer: Lawrence Gripper <info@grippers.co.uk>
  license: MIT
  vendor: LawrenceGripper
  formats:
  - deb
  - rpm
  dependencies:
  - git
  recommends:
  - rpm

dockers:
  - goos: linux
    goarch: amd64
    binaries:
    - azbrowse
    # Templates of the Docker image names.
    image_templates:
    - "lawrencegripper/azbrowse:latest"
    - "lawrencegripper/azbrowse:{{ .Tag }}"
    - "lawrencegripper/azbrowse:v{{ .Major }}"
    skip_push: false
    dockerfile: Dockerfile
    # Template of the docker build flags.
    build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.name={{.ProjectName}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
