name: ARM Spec Updater

on:
  workflow_dispatch:
  schedule:
  - cron: "0 17 * * 1"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run Checks, Tests and Build
      uses: devcontainers/ci@v0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GHACTIONS_SECRET }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        imageName: ghcr.io/lawrencegripper/azbrowse/devcontainer
        cacheFrom: ghcr.io/lawrencegripper/azbrowse/devcontainer
        push: never
        refFilterForPush: refs/heads/main
        runCmd: make swagger-update && make swagger-codegen
    
    - name: Sort file permissions
      run: sudo chown -R $(whoami) .

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 🧹 Update ARM Specs
        title: Update ARM Specs
        body: Automated PR generated by the ARM Spec Updater action
        branch: update-arm-spec
        base: main
