name: ARM Spec Updater

on:
  workflow_dispatch:
  schedule:
  - cron: "0 17 * * 1"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run Checks, Tests and Build
      uses: devcontainers/ci@v0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GHACTIONS_SECRET }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        imageName: ghcr.io/lawrencegripper/azbrowse/devcontainer
        cacheFrom: ghcr.io/lawrencegripper/azbrowse/devcontainer
        push: never
        refFilterForPush: refs/heads/main
        runCmd: make swagger-codegen && make swagger-create-pr
