name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 12 * * 1"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Flagging stale issue. Actions will close this issue in the next 5 days unless action is taken.'
        stale-pr-message: 'Flagging stale pull request. Actions will close this PR in the next 5 days unless action is taken. Tag with awaiting-approval to avoid.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 30
        days-before-close: 5
        exempt-issue-label: 'no-stale'
        exempt-pr-label: 'awaiting-approval'
